fullnameOverride: logstash
image: "docker.elastic.co/logstash/logstash"

extraEnvs:
  - name: ELASTICSEARCH_HOSTS
    value: "data-0.data-headless.elastic:9200 data-1.data-headless.elastic:9200 data-2.data-headless.elastic:9200"
  - name: ELASTICSEARCH_INPUT_INDEX
    value: "alert-notifications"
  # - name: ELASTICSEARCH_USERNAME
  #   valueFrom:
  #     secretKeyRef:
  #       name: elastic-credentials
  #       key: ES_USERNAME
  # - name: ELASTICSEARCH_PASSWORD
  #   valueFrom:
  #     secretKeyRef:
  #       name: elastic-credentials
  #       key: ES_PASSWORD
  - name: MICROSOFT_TEAMS_WEBHOOK
    valueFrom:
      secretKeyRef:
        name: webhook-url
        key: MICROSOFT_TEAMS_WEBHOOK
  # - name: HTTP_PROXY
  #   value: "http://proxy.example.com"

# extraVolumes:
#   - name: elasticsearch-ca-cert
#     secret:
#       secretName: logstash-certificates-es-https

# extraVolumeMounts:
#   - name: elasticsearch-ca-cert
#     mountPath: /usr/share/certs/elasticsearch-ca.pem
#     subPath: elasticsearch-ca.pem

resources:
  requests:
    cpu: 300m

podSecurityPolicy:
  create: true

rbac:
  create: true
